name: Main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/frontend.yaml@configure_js_services  # TODO: set to @main
    secrets: inherit
