name: Main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-frontend:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/test-javascript-code.yaml@configure_js_services # TODO: set to @main
    secrets: inherit
